---
author:
  name: Bruno Bruno
  picture: 117016
body: "Hi guys, \r\n\r\nJust keep getting error messages after running the following
  code:\r\n\r\n<code>\r\nfrom robofab.world import CurrentFont\r\n\r\nmyFont = CurrentFont()\r\n\r\nfor
  myGlyph in myFont:\r\n\tprint myGlyph.name\r\n\tmyGlyph.autoContourOrder()\r\n\tmyGlyph.correctDirection()\r\n\tmyGlyph.update()\r\n\tfor
  myContours in myGlyph.contours:\r\n\t\tmyContours.autoStartSegment()\r\n\t\r\nprint
  \"done now\"\r\n</code>\r\n\r\nThis is the error message:\r\n<code>\r\nTraceback
  (most recent call last):\r\n  File \"<string>\", line 16, in ?\r\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.3/lib/python2.3/site-packages/RoboFab/robofab/objects/objectsBase.py\",
  line 2129, in autoStartSegment\r\n    on = segment.onCurve\r\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.3/lib/python2.3/site-packages/RoboFab/robofab/objects/objectsBase.py\",
  line 2330, in _get_onCurve\r\n    return self.points[-1]\r\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.3/lib/python2.3/site-packages/RoboFab/robofab/objects/objectsFL.py\",
  line 1942, in _get_points\r\n    node = self._node\r\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.3/lib/python2.3/site-packages/RoboFab/robofab/objects/objectsFL.py\",
  line 1880, in _get__node\r\n    return glyph.nodes[self._nodeIndex]\r\nIndexError:
  list index out of range\r\n</code>\r\n\r\nThe weird thing is (after running it a
  second time) it will not bump into the same problem again, but rather continues
  to the next problem, if that makes sense. After a while the script runs fine. Really
  have no clue here.\r\n\r\nThanks,\r\n\r\nBruno"
comments:
- author:
    name: Bruno Bruno
    picture: 117016
  body: "Ok, for the interested: \r\nFollowing should work, cheers\r\n\r\n<code>\r\nfrom
    robofab.world import CurrentFont\r\n\r\nmyFont = CurrentFont()\r\nprint myFont.info.postscriptFullName\r\n\r\nmyGlyph
    = myFont.keys\r\n\r\nfor myGlyph in myFont:\r\n> print myGlyph.name\r\n> myGlyph.autoContourOrder()\r\n>
    myGlyph.correctDirection()\r\n> > for myContours in myGlyph:\r\n> > myContours.autoStartSegment()\r\n>
    myGlyph.update()\r\n\r\nprint \"done now\"\r\n</code>"
  created: '2009-10-07 02:07:51'
date: '2009-10-06 13:30:37'
node_type: forum
title: 'IndexError: list index out of range (Solved)'

---
